/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of my resources */
        get: operations["get"];
        /**
         * Replace a resource
         * @description A FILE keeps its file: only title, body, goal and pin change, and the type stays FILE.
         */
        put: operations["update"];
        post?: never;
        /**
         * Delete a resource for good
         * @description A FILE resource's file is deleted with it.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change my name, timezone and promotional-email choice
         * @description A new timezone moves "today" for check-ins, streaks and reminders from now on; days already logged keep their dates.
         */
        put: operations["update_1"];
        post?: never;
        /**
         * Delete my account and everything in it
         * @description Habits, check-ins, goals, notes, links, files, notifications and sessions — for good. Needs the password when the account has one.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of my habits */
        get: operations["get_1"];
        /** Replace a habit's details and schedule */
        put: operations["update_2"];
        post?: never;
        /**
         * Delete a habit for good
         * @description Its check-ins and reminders go too, and the XP and goal progress they earned. To stop a habit but keep its history, archive it instead.
         */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}/goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Link a habit to one of my active goals, or change the link's target days */
        put: operations["linkGoal"];
        post?: never;
        /** Take a habit off its goal */
        delete: operations["unlinkGoal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of my goals */
        get: operations["get_2"];
        /** Replace a goal's title, description and target date */
        put: operations["update_3"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My resources, pinned first then newest */
        get: operations["list"];
        put?: never;
        /**
         * Save a note or a link
         * @description Files are uploaded with POST /api/resources/files.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{id}/unpin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unpin a resource */
        post: operations["unpin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin a resource so it is listed first */
        post: operations["pin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a file as a resource
         * @description multipart/form-data: the `file` part plus title, body, goalId, pinned as form fields. PNG, JPEG, WebP, GIF, PDF or text (.txt, .md), at most 10 MB; 100 MB per user in total. The type is detected from the bytes and must match the file's extension.
         */
        post: operations["createFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save this browser's push subscription
         * @description The body is the browser's PushSubscription.toJSON(). Only the browsers' own push services are accepted (FCM, Mozilla, Apple, Windows). Saving the same browser again is fine.
         */
        post: operations["subscribe"];
        /** Forget this browser's push subscription (on sign-out, or when notifications are turned off) */
        delete: operations["unsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark one notification read; doing it twice is fine */
        post: operations["markRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark all my notifications read */
        post: operations["markAllRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My habits, newest first by default */
        get: operations["list_1"];
        put?: never;
        /** Create a habit */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bring an archived habit back */
        post: operations["unarchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a habit (the soft delete); its history is kept */
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{habitId}/rest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rest the habit on a day (today by default)
         * @description A rest day neither breaks nor extends the streak and isn't expected in completion rates. Daily and chosen-weekday habits, on a day they're due, not yet done. Per habit and Mon–Sun week: the 1st is free, the 2nd costs 100 XP, the 3rd 200 (from the level's xpBalance), no 4th. Same dates as a check-in. A check-in on the day ends the rest.
         */
        post: operations["rest"];
        /** Take a rest day back; its XP is refunded */
        delete: operations["cancelRest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{habitId}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check in: set a day's count for a habit (today by default); repeating it is safe */
        post: operations["checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My goals, newest first by default */
        get: operations["list_2"];
        put?: never;
        /** Create a goal */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{id}/achieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a goal achieved (my call, not automatic at 100 %) */
        post: operations["achieve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Give a goal up; its habits stay linked */
        post: operations["abandon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an email/password account and sign in */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a new access token using the refresh token cookie; the cookie is rotated */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Choose a new password with the emailed token, and sign in
         * @description Signs the account out on every other device and retires its other reset links.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a password reset link
         * @description Always 202 with the same message, whether or not the email has an account. The link is <frontend>/reset-password#token=…, valid 30 minutes, single use. At most one email a minute and 5 an hour per account. A Google-only account gets a link to set its first password.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change my password
         * @description Needs the current password. Signs out every other session and retires reset links; this session gets a fresh token pair. An account that only signs in with Google has no password yet: 409 — it sets one through "forgot password" (or, once Google sign-in exists, here after a fresh Google sign-in).
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out: revoke the refresh token and clear its cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in (or up) with Google
         * @description Send the ID token Google Identity Services gives the page. Finds the account by Google id, then by email (linking it), else creates one. Linking an account whose email was never confirmed removes its password and signs it out everywhere first.
         */
        post: operations["google"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm my email address with the emailed token
         * @description Public: the link may be opened on a device that isn't signed in. Single use, valid 24 hours.
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send me a new confirmation email
         * @description One sent at sign-up already. At most one a minute and 5 an hour; past that nothing is sent.
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a FILE resource's file
         * @description Always as an attachment, with the stored (detected) type. Send the bearer token: fetch it and save or show the blob — a plain link can't carry the header.
         */
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether push is on, and the key to subscribe with */
        get: operations["publicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My notifications, unread first, then newest first */
        get: operations["list_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many notifications are unread (cheap to poll) */
        get: operations["unreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/level": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My XP, level and tier
         * @description Computed from all my habits (archived too) and achieved goals; XP is never lost when a streak breaks. +10 per done day that counts for the streak, +5 more while the streak is at least 7 days (1 week), +50/+200/+500/+1500 at 7/30/100/365 days (1/4/14/52 weeks), +500 per achieved goal.
         */
        get: operations["level"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download all my data as JSON
         * @description Profile, habits (archived too), every check-in, goals, notes, links and file entries (not the files themselves — download those one by one). Same shapes as the rest of the API.
         */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{habitId}/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The habit's current and longest streak (days, or weeks for N-times-a-week habits) */
        get: operations["streak"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{habitId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Completion rate over the last 7 and 30 days */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{habitId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A habit's check-ins between two days, newest first (default: the last 30 days) */
        get: operations["logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How far a goal has come, in total and per linked habit */
        get: operations["progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{goalId}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A goal's resources, pinned first then newest */
        get: operations["listForGoal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My home screen: today, completion, highlights, goals and level
         * @description Active habits only, in my timezone. `today` lists every habit with today's count, whether it's due and its current streak. `completion` gives 7/30/90-day rates, overall and per habit, each with the previous period of the same length and the change. `atRisk`: streaks of 3+ that end unless something happens today. `best` / `slipping`: top 3 by 30-day rate / by drop. `goals`: active goals with progress. `level`: as GET /api/me/level. Same numbers as the habit, goal and level endpoints.
         */
        get: operations["dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My patterns: heatmap, weekdays, time of day
         * @description Active habits, in my timezone. `heatmap`: the last 365 days, each with done / expected habits (N-a-week habits only add to the days they were done). `weekdays`: completion by weekday over the last 12 full weeks, daily and chosen-weekday habits only, with the weakest and strongest day. `hours`: when done check-ins of the last 90 days happened (first check-in, same-day only), with the peak hour.
         */
        get: operations["patterns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ResourceRequest: {
            /**
             * @example LINK
             * @enum {string}
             */
            type: "NOTE" | "LINK" | "FILE";
            /** @example Couch to 5K plan */
            title: string;
            /** @description Markdown. Required for a NOTE; an optional comment for a LINK. */
            body?: string;
            /**
             * @description http or https address. Required for a LINK, not allowed on a NOTE.
             * @example https://example.com/plan
             */
            url?: string;
            /**
             * Format: int64
             * @description The goal it belongs to. Omit for a stand-alone resource.
             * @example 1
             */
            goalId?: number;
            /** @description Shown first. Defaults to false. */
            pinned?: boolean;
        };
        HttpResponse: {
            status?: string;
            success?: boolean;
            message?: string;
            errorCode?: string;
            correlationId?: string;
            fields?: {
                [key: string]: string;
            };
            payload?: unknown;
        };
        UpdateProfileRequest: {
            name: string;
            /**
             * @description IANA region name; the web app sends the browser's (Intl…resolvedOptions().timeZone)
             * @example Asia/Dhaka
             */
            timezone: string;
            /** @description Promotional email. Off unless the user turns it on. */
            marketingEmails: boolean;
        };
        /** @description SPECIFIC_DAYS needs days; X_TIMES_PER_WEEK needs timesPerWeek (1-6); DAILY needs neither */
        FrequencyConfig: {
            /**
             * @example [
             *       "MONDAY",
             *       "WEDNESDAY",
             *       "FRIDAY"
             *     ]
             */
            days?: ("MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY")[];
            /**
             * Format: int32
             * @example 3
             */
            timesPerWeek?: number;
        };
        HabitRequest: {
            /** @example Read 20 pages */
            name: string;
            /** @example Learning */
            category?: string;
            /**
             * @description BUILD (default): check in when done. QUIT: check in when you slip; daily, no reminder, target 1, no goal. Set at creation; it can't change.
             * @enum {string}
             */
            kind?: "BUILD" | "QUIT";
            /**
             * @example SPECIFIC_DAYS
             * @enum {string}
             */
            frequencyType: "DAILY" | "SPECIFIC_DAYS" | "X_TIMES_PER_WEEK";
            frequencyConfig?: components["schemas"]["FrequencyConfig"];
            /**
             * Format: int32
             * @description Completions a day needs to count as done. Defaults to 1.
             * @example 1
             */
            targetCount?: number;
            /**
             * @description What is counted, shown with the target: "8 glasses". Optional.
             * @example glasses
             */
            unit?: string;
            /**
             * @description Reminder time of day (HH:mm) in your timezone. Omit for no reminder.
             * @example 07:30
             */
            reminderTime?: string;
        };
        GoalLinkRequest: {
            /**
             * Format: int64
             * @example 1
             */
            goalId: number;
            /**
             * Format: int32
             * @description Done days that make this habit 'built' for the goal.
             * @example 60
             */
            goalTargetDays: number;
        };
        GoalRequest: {
            /** @example Run a half marathon */
            title: string;
            /** @example Finish the city half marathon in under two hours */
            description?: string;
            /**
             * Format: date
             * @description Optional deadline. Omit for none.
             * @example 2026-12-31
             */
            targetDate?: string;
        };
        ResourceFileRequest: {
            /** @example Week 1 plan */
            title: string;
            /** @description An optional comment about the file (Markdown). */
            body?: string;
            /**
             * Format: int64
             * @description The goal it belongs to. Omit for a stand-alone resource.
             * @example 1
             */
            goalId?: number;
            /** @description Shown first. Defaults to false. */
            pinned?: boolean;
        };
        Keys: {
            p256dh: string;
            auth: string;
        };
        SubscribeRequest: {
            endpoint: string;
            keys: components["schemas"]["Keys"];
        };
        RestRequest: {
            /**
             * Format: date
             * @description The day, in your timezone. Defaults to today; at most 7 days back.
             * @example 2026-10-10
             */
            date?: string;
        };
        CheckInRequest: {
            /**
             * Format: date
             * @description The day, in your timezone. Defaults to today; at most 7 days back.
             * @example 2026-09-30
             */
            date?: string;
            /**
             * Format: int32
             * @description The day's total (not +1). Defaults to the habit's targetCount; 0 undoes.
             * @example 1
             */
            completedCount?: number;
            /** @description Omit to keep the current note; empty string clears it. */
            note?: string;
        };
        RegisterRequest: {
            /**
             * Format: email
             * @example nayeem@example.com
             */
            email: string;
            password: string;
            /** @example Nayeem */
            name: string;
            /**
             * @description IANA timezone; decides what "today" is for check-ins. Defaults to UTC.
             * @example Asia/Dhaka
             */
            timezone?: string;
        };
        ResetPasswordRequest: {
            /** @description The token from the emailed link (after #token=) */
            token: string;
            newPassword: string;
        };
        ForgotPasswordRequest: {
            /**
             * Format: email
             * @example nayeem@example.com
             */
            email: string;
        };
        ChangePasswordRequest: {
            /** @description Required when the account has a password */
            currentPassword?: string;
            newPassword: string;
        };
        LoginRequest: {
            /** @example nayeem@example.com */
            email: string;
            password: string;
        };
        GoogleSignInRequest: {
            /** @description The credential from Google Identity Services (a Google-signed ID token) */
            idToken: string;
            /**
             * @description IANA timezone, used only when this creates the account. Defaults to UTC.
             * @example Asia/Dhaka
             */
            timezone?: string;
        };
        VerifyEmailRequest: {
            /** @description The token from the emailed link (after #token=) */
            token: string;
        };
        AccountExport: {
            /** Format: date-time */
            exportedAt?: string;
            profile?: components["schemas"]["UserResponse"];
            habits?: components["schemas"]["HabitResponse"][];
            checkIns?: components["schemas"]["ExportedCheckIn"][];
            goals?: components["schemas"]["GoalResponse"][];
            resources?: components["schemas"]["ResourceResponse"][];
        };
        ExportedCheckIn: {
            /** Format: int64 */
            habitId?: number;
            /** Format: date */
            date?: string;
            /** Format: int32 */
            completedCount?: number;
            /** Format: int32 */
            targetCount?: number;
            note?: string;
        };
        FileInfo: {
            /** @example Week 1 plan.pdf */
            name?: string;
            /**
             * @description Detected from the file's bytes
             * @example application/pdf
             */
            contentType?: string;
            /**
             * Format: int64
             * @example 48213
             */
            sizeBytes?: number;
        };
        GoalResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            /** Format: date */
            targetDate?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "ACHIEVED" | "ABANDONED";
            /** Format: date-time */
            achievedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        HabitResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            category?: string;
            /** @enum {string} */
            kind?: "BUILD" | "QUIT";
            /** @enum {string} */
            frequencyType?: "DAILY" | "SPECIFIC_DAYS" | "X_TIMES_PER_WEEK";
            frequencyConfig?: components["schemas"]["FrequencyConfig"];
            /** Format: int32 */
            targetCount?: number;
            unit?: string;
            reminderTime?: string;
            archived?: boolean;
            /** Format: int64 */
            goalId?: number;
            /** Format: int32 */
            goalTargetDays?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ResourceResponse: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            type?: "NOTE" | "LINK" | "FILE";
            title?: string;
            body?: string;
            url?: string;
            /** Format: int64 */
            goalId?: number;
            /** @description The uploaded file; only for a FILE resource */
            file?: components["schemas"]["FileInfo"];
            pinned?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        UserResponse: {
            /** Format: int64 */
            id?: number;
            email?: string;
            name?: string;
            /** @enum {string} */
            authProvider?: "LOCAL" | "GOOGLE";
            timezone?: string;
            emailVerified?: boolean;
            marketingEmails?: boolean;
            /** @enum {string} */
            plan?: "FREE" | "PRO";
        };
        UnsubscribeRequest: {
            endpoint: string;
        };
        DeleteAccountRequest: {
            /** @description Required when the account has a password */
            password?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such resource, or not yours (RESOURCE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceRequest"];
            };
        };
        responses: {
            /** @description The updated resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields (VALIDATION_FAILED, RESOURCE_INVALID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such resource or goal, or not yours */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such resource, or not yours (RESOURCE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description The updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields, or not an IANA region name (USER_INVALID_TIMEZONE) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Deleted; the tokens stop working */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wrong password (AUTH_WRONG_PASSWORD) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many wrong passwords (RATE_LIMITED) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The habit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitRequest"];
            };
        };
        responses: {
            /** @description The updated habit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields or schedule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    linkGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalLinkRequest"];
            };
        };
        responses: {
            /** @description The habit, with goalId and goalTargetDays */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit or goal, or not yours (HABIT_NOT_FOUND, GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description The habit is archived (HABIT_ARCHIVED) or the goal isn't active (GOAL_NOT_ACTIVE) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    unlinkGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The habit; unlinking an unlinked habit is fine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The goal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such goal, or not yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalRequest"];
            };
        };
        responses: {
            /** @description The updated goal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such goal, or not yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description Only this goal's resources */
                goalId?: number;
                /** @description NOTE, LINK or FILE */
                type?: "NOTE" | "LINK" | "FILE";
                /** @description Title contains this text, any case */
                q?: string;
                page?: number;
                /** @description 1-100 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of resources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceRequest"];
            };
        };
        responses: {
            /** @description Created; Location points at the resource */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields, fields that don't fit the type, or type FILE (RESOURCE_INVALID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description The goal isn't yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    unpin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such resource, or not yours (RESOURCE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    pin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resource; pinning twice is fine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such resource, or not yours (RESOURCE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    createFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    request?: components["schemas"]["ResourceFileRequest"];
                };
            };
        };
        responses: {
            /** @description Created; Location points at the resource */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Missing file or invalid fields (MALFORMED_REQUEST, VALIDATION_FAILED, FILE_EMPTY) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description The goal isn't yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description File over 10 MB, or your storage is full (FILE_TOO_LARGE, FILE_QUOTA_EXCEEDED) */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description File type not allowed (FILE_TYPE_NOT_ALLOWED) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeRequest"];
            };
        };
        responses: {
            /** @description Saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Not a browser push subscription (PUSH_SUBSCRIPTION_INVALID) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnsubscribeRequest"];
            };
        };
        responses: {
            /** @description Forgotten; also when it wasn't saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The notification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such notification, or not yours (NOTIFICATION_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description How many were unread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                /** @description true for the archived ones */
                archived?: boolean;
                page?: number;
                /** @description 1-100 */
                size?: number;
                /** @description createdAt or name */
                sortBy?: string;
                /** @description asc or desc */
                sortDir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of habits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitRequest"];
            };
        };
        responses: {
            /** @description Created; Location points at the habit */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields, or a schedule that doesn't fit the frequency type (HABIT_INVALID_FREQUENCY) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    unarchive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The habit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived habit; archiving twice is fine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    rest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habitId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RestRequest"];
            };
        };
        responses: {
            /** @description The day's log, with rest = true; resting twice is fine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Not this habit or day (REST_NOT_ALLOWED), or a date out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Already done (REST_DAY_DONE), 3 used this week (REST_LIMIT_REACHED), not enough XP (XP_NOT_ENOUGH), or archived */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    cancelRest: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                habitId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Done; also when the day wasn't a rest day */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habitId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CheckInRequest"];
            };
        };
        responses: {
            /** @description The day's log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Future day, more than 7 days back, or before the habit existed (LOG_DATE_OUT_OF_RANGE) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description The habit is archived (HABIT_ARCHIVED) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                /** @description ACTIVE, ACHIEVED or ABANDONED; omit for all */
                status?: "ACTIVE" | "ACHIEVED" | "ABANDONED";
                page?: number;
                /** @description 1-100 */
                size?: number;
                /** @description createdAt, title or targetDate */
                sortBy?: string;
                /** @description asc or desc */
                sortDir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of goals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalRequest"];
            };
        };
        responses: {
            /** @description Created; Location points at the goal */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    achieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The goal, ACHIEVED with achievedAt; repeating it is fine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such goal, or not yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Already abandoned (GOAL_ALREADY_CLOSED) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    abandon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The goal, ABANDONED; repeating it is fine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such goal, or not yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Already achieved (GOAL_ALREADY_CLOSED) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created; access token in the body, refresh token cookie set */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields or unknown timezone */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Email already registered (USER_EMAIL_TAKEN) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description New access token; new refresh token cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Missing, expired, revoked or reused refresh token (AUTH_INVALID_REFRESH_TOKEN) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password set; signed in (access token in the body, refresh cookie set) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid, expired or used link (AUTH_INVALID_RESET_TOKEN), or a password under 8 characters (VALIDATION_FAILED) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Accepted (an email is sent only if the account exists) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Not an email address (VALIDATION_FAILED) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Changed; new access token in the body, new refresh cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Wrong current password (AUTH_WRONG_PASSWORD), or a new password under 8 characters (VALIDATION_FAILED) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description The account has no password yet (AUTH_PASSWORD_NOT_SET) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Signed out (also when there was nothing to revoke) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in; access token in the body, refresh token cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Wrong email or password (AUTH_INVALID_CREDENTIALS) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    google: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleSignInRequest"];
            };
        };
        responses: {
            /** @description Signed in; access token in the body, refresh token cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid token (AUTH_INVALID_GOOGLE_TOKEN) or unverified Google email (AUTH_GOOGLE_EMAIL_UNVERIFIED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Email confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid, expired or used link (AUTH_INVALID_VERIFY_TOKEN) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Already confirmed (AUTH_EMAIL_ALREADY_VERIFIED) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file's bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description No such resource or not yours (RESOURCE_NOT_FOUND), or it has no file (FILE_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    publicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description enabled, publicKey (null when off) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                page?: number;
                /** @description 1-100 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    unreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The unread count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    level: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The level */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description devhabit-export.json, as an attachment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountExport"];
                };
            };
        };
    };
    streak: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habitId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The streak; today or this week never breaks it while in progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habitId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Done vs expected days per window; today counts once it's done */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    logs: {
        parameters: {
            query?: {
                /** @description First day, inclusive */
                from?: string;
                /** @description Last day, inclusive; defaults to today */
                to?: string;
                page?: number;
                /** @description 1-100 */
                size?: number;
            };
            header?: never;
            path: {
                habitId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description from after to, or more than 366 days apart */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    progress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress 0-100 %, computed from the habits' done days */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such goal, or not yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    listForGoal: {
        parameters: {
            query?: {
                page?: number;
                /** @description 1-100 */
                size?: number;
            };
            header?: never;
            path: {
                goalId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of resources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such goal, or not yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The dashboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    patterns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The patterns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Missing or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
}
