/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/habits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of my habits */
        get: operations["get"];
        /** Replace a habit's details and schedule */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}/goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Link a habit to one of my active goals, or change the link's target days */
        put: operations["linkGoal"];
        post?: never;
        /** Take a habit off its goal */
        delete: operations["unlinkGoal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of my goals */
        get: operations["get_1"];
        /** Replace a goal's title, description and target date */
        put: operations["update_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark one notification read; doing it twice is fine */
        post: operations["markRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark all my notifications read */
        post: operations["markAllRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My habits, newest first by default */
        get: operations["list"];
        put?: never;
        /** Create a habit */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bring an archived habit back */
        post: operations["unarchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a habit (the soft delete); its history is kept */
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{habitId}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check in: set a day's count for a habit (today by default); repeating it is safe */
        post: operations["checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My goals, newest first by default */
        get: operations["list_1"];
        put?: never;
        /** Create a goal */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{id}/achieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a goal achieved (my call, not automatic at 100 %) */
        post: operations["achieve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Give a goal up; its habits stay linked */
        post: operations["abandon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an email/password account and sign in */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a new access token using the refresh token cookie; the cookie is rotated */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out: revoke the refresh token and clear its cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My notifications, unread first, then newest first */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How many notifications are unread (cheap to poll) */
        get: operations["unreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{habitId}/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The habit's current and longest streak (days, or weeks for N-times-a-week habits) */
        get: operations["streak"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{habitId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Completion rate over the last 7 and 30 days */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{habitId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A habit's check-ins between two days, newest first (default: the last 30 days) */
        get: operations["logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How far a goal has come, in total and per linked habit */
        get: operations["progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description SPECIFIC_DAYS needs days; X_TIMES_PER_WEEK needs timesPerWeek (1-6); DAILY needs neither */
        FrequencyConfig: {
            /**
             * @example [
             *       "MONDAY",
             *       "WEDNESDAY",
             *       "FRIDAY"
             *     ]
             */
            days?: ("MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY")[];
            /**
             * Format: int32
             * @example 3
             */
            timesPerWeek?: number;
        };
        HabitRequest: {
            /** @example Read 20 pages */
            name: string;
            /** @example Learning */
            category?: string;
            /**
             * @example SPECIFIC_DAYS
             * @enum {string}
             */
            frequencyType: "DAILY" | "SPECIFIC_DAYS" | "X_TIMES_PER_WEEK";
            frequencyConfig?: components["schemas"]["FrequencyConfig"];
            /**
             * Format: int32
             * @description Completions a day needs to count as done. Defaults to 1.
             * @example 1
             */
            targetCount?: number;
            /**
             * @description Reminder time of day (HH:mm) in your timezone. Omit for no reminder.
             * @example 07:30
             */
            reminderTime?: string;
        };
        HttpResponse: {
            status?: string;
            success?: boolean;
            message?: string;
            errorCode?: string;
            correlationId?: string;
            fields?: {
                [key: string]: string;
            };
            payload?: unknown;
        };
        GoalLinkRequest: {
            /**
             * Format: int64
             * @example 1
             */
            goalId: number;
            /**
             * Format: int32
             * @description Done days that make this habit 'built' for the goal.
             * @example 60
             */
            goalTargetDays: number;
        };
        GoalRequest: {
            /** @example Run a half marathon */
            title: string;
            /** @example Finish the city half marathon in under two hours */
            description?: string;
            /**
             * Format: date
             * @description Optional deadline. Omit for none.
             * @example 2026-12-31
             */
            targetDate?: string;
        };
        CheckInRequest: {
            /**
             * Format: date
             * @description The day, in your timezone. Defaults to today; at most 7 days back.
             * @example 2026-09-30
             */
            date?: string;
            /**
             * Format: int32
             * @description The day's total (not +1). Defaults to the habit's targetCount; 0 undoes.
             * @example 1
             */
            completedCount?: number;
            /** @description Omit to keep the current note; empty string clears it. */
            note?: string;
        };
        RegisterRequest: {
            /**
             * Format: email
             * @example nayeem@example.com
             */
            email: string;
            password: string;
            /** @example Nayeem */
            name: string;
            /**
             * @description IANA timezone; decides what "today" is for check-ins. Defaults to UTC.
             * @example Asia/Dhaka
             */
            timezone?: string;
        };
        LoginRequest: {
            /** @example nayeem@example.com */
            email: string;
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The habit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitRequest"];
            };
        };
        responses: {
            /** @description The updated habit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields or schedule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    linkGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalLinkRequest"];
            };
        };
        responses: {
            /** @description The habit, with goalId and goalTargetDays */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit or goal, or not yours (HABIT_NOT_FOUND, GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description The habit is archived (HABIT_ARCHIVED) or the goal isn't active (GOAL_NOT_ACTIVE) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    unlinkGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The habit; unlinking an unlinked habit is fine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The goal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such goal, or not yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalRequest"];
            };
        };
        responses: {
            /** @description The updated goal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such goal, or not yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The notification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such notification, or not yours (NOTIFICATION_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description How many were unread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description true for the archived ones */
                archived?: boolean;
                page?: number;
                /** @description 1-100 */
                size?: number;
                /** @description createdAt or name */
                sortBy?: string;
                /** @description asc or desc */
                sortDir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of habits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitRequest"];
            };
        };
        responses: {
            /** @description Created; Location points at the habit */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields, or a schedule that doesn't fit the frequency type (HABIT_INVALID_FREQUENCY) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    unarchive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The habit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archived habit; archiving twice is fine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habitId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CheckInRequest"];
            };
        };
        responses: {
            /** @description The day's log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Future day, more than 7 days back, or before the habit existed (LOG_DATE_OUT_OF_RANGE) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description The habit is archived (HABIT_ARCHIVED) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                /** @description ACTIVE, ACHIEVED or ABANDONED; omit for all */
                status?: "ACTIVE" | "ACHIEVED" | "ABANDONED";
                page?: number;
                /** @description 1-100 */
                size?: number;
                /** @description createdAt, title or targetDate */
                sortBy?: string;
                /** @description asc or desc */
                sortDir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of goals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalRequest"];
            };
        };
        responses: {
            /** @description Created; Location points at the goal */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    achieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The goal, ACHIEVED with achievedAt; repeating it is fine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such goal, or not yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Already abandoned (GOAL_ALREADY_CLOSED) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    abandon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The goal, ABANDONED; repeating it is fine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such goal, or not yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Already achieved (GOAL_ALREADY_CLOSED) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created; access token in the body, refresh token cookie set */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Invalid fields or unknown timezone */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Email already registered (USER_EMAIL_TAKEN) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description New access token; new refresh token cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Missing, expired, revoked or reused refresh token (AUTH_INVALID_REFRESH_TOKEN) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Signed out (also when there was nothing to revoke) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in; access token in the body, refresh token cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Wrong email or password (AUTH_INVALID_CREDENTIALS) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                page?: number;
                /** @description 1-100 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    unreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The unread count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    streak: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habitId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The streak; today or this week never breaks it while in progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                habitId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Done vs expected days per window; today counts once it's done */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    logs: {
        parameters: {
            query?: {
                /** @description First day, inclusive */
                from?: string;
                /** @description Last day, inclusive; defaults to today */
                to?: string;
                page?: number;
                /** @description 1-100 */
                size?: number;
            };
            header?: never;
            path: {
                habitId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description from after to, or more than 366 days apart */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such habit, or not yours (HABIT_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    progress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress 0-100 %, computed from the habits' done days */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description No such goal, or not yours (GOAL_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
            /** @description Missing or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HttpResponse"];
                };
            };
        };
    };
}
